Fix ENTRYPOINT/CMD, unlock psecrets on startup
- Fix my swapped ENTRYPOINT and CMD statements
- Add unlock-psecrets script
- Fix unlocking psecrets on startup
- Prevent unlock-psecrets variables from polluting the shell

diff --git a/docker/psybin/unlock-psecrets b/docker/psybin/unlock-psecrets
--- a/docker/psybin/unlock-psecrets
+++ b/docker/psybin/unlock-psecrets
@@ -30,31 +30,26 @@ remoteuri="file:///psyops/submod/psyops-secrets"
 # The psyops-secrets repo has a script to symlink its config files into the homedir... if it exists, the repo was successfully decrypted
 secretssymlink="$repopath/symlink.sh"
 
-test_psecrets() {
-    return $(test -e "$secretssymlink")
-}
+psecrets unlock \
+    --import-secret-key "$importseckey" \
+    --import-public-key "$importpubkey" \
+    --import-ownertrust-db "$importtrust" \
+    --gpg-secret-key-id "$seckeyid" \
+    --gpg-passphrase-file "$gpgpassfile" \
+    --ssh-encrypted-private-key "$encsshkey" \
+    --ssh-decrypted-private-key "$decsshkey" \
+    --ssh-public-key "$pubsshkey" \
+    --git-branch "$branchname" \
+    --git-remote "$remotename" \
+    --git-remote-uri "$remoteuri" \
+    --git-local-repository "$repopath" \
+    --clone-first \
+    || true
 
-setup_psecrets() {
-    psecrets unlock \
-        --import-secret-key "$importseckey" \
-        --import-public-key "$importpubkey" \
-        --import-ownertrust-db "$importtrust" \
-        --gpg-secret-key-id "$seckeyid" \
-        --gpg-passphrase-file "$gpgpassfile" \
-        --ssh-encrypted-private-key "$encsshkey" \
-        --ssh-decrypted-private-key "$decsshkey" \
-        --ssh-public-key "$pubsshkey" \
-        --git-branch "$branchname" \
-        --git-remote "$remotename" \
-        --git-remote-uri "$remoteuri" \
-        --git-local-repository "$repopath" \
-        --clone-first
-
-    if test_psecrets; then
-        $secretssymlink
-        echo "Secrets decrypted and symlinked successfully"
-    else
-        echo "Secrets NOT decrypted, commands that rely on config files (doctl, gandi, aws, ...) will fail!"
-        echo "Run setup_psecrets to attempt to decrypt the secrets repo again."
-    fi
-}
+if test -e "$secretssymlink"; then
+    $secretssymlink
+    echo "Secrets decrypted and symlinked successfully"
+else
+    echo "Secrets NOT decrypted, commands that rely on config files (doctl, gandi, aws, ...) will fail!"
+    echo "Run $0 to attempt to decrypt the secrets repo again."
+fi
